### ISSUE TITLE
Change default license

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/disease-mappings#14]
While we are still working on propagating license statements, can we use 

```
license: https://github.com/mapping-commons/mapping-commons.github.io/blob/main/docs/original_license_applies.md
```

as a default license for all mapping sets in dmc (disease mapping commons) that do not have one already?

https://github.com/mapping-commons/mapping-commons.github.io/blob/main/docs/original_license_applies.md

**Comment by hrshdhgd** [comment]
PR #15
