### ISSUE TITLE
Document ICD10 mapping sources

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/disease-mappings#6]
@sabrinatoro

Provide a list of URLs that you think hold good quality ICD10CM mappings, e.g.:

- https://www.nlm.nih.gov/research/umls/mapping_projects/snomedct_to_icd10cm.html

**Comment by sabrinatoro** [comment]
These are all the ICD10 mappings I found. 
Note that I don't know whether these are of good quality or not. 

Orphanet - ICD-10
http://www.orphadata.org/cgi-bin/ORPHAnomenclature.html

NCIT- ICD10 
https://ncit.nci.nih.gov/ncitbrowser/pages/mapping_search.jsf?nav_type=mappings

SNOMED - ICD10 
https://www.nlm.nih.gov/research/umls/mapping_projects/snomedct_to_icd10cm.html 
https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/mapping_projects/index.html

Note that most of what I found uses the SNOMED-ICD10 mapping for their own mapping. So the SNOMED-ICD10 seems to be the best reference.

**Comment by matentzn** [comment]
@hrshdhgd is already working on Orphanet in #5 
@joeflack4 is working on SNOMED in #8

**Comment by matentzn** [comment]
Issue is addressed sufficiently for now. Thanks all.
