### ISSUE TITLE
Build ingest pipeline for SNOMED-ICD10 mappings

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/disease-mappings#8]
https://www.nlm.nih.gov/research/umls/mapping_projects/snomedct_to_icd10cm.html

this should be realised as a SSSOM py extension, analogous to:

https://github.com/mapping-commons/sssom-py/blob/52ad5ae07ff1ee1dc14bfa84ba7cf02c92db7640/sssom/parsers.py#L415

If this turns out cumbersome, a stand alone python script here in mapping commons will do as well!

**Comment by matentzn** [comment]
@joeflack4

**Comment by joeflack4** [comment]
Related: #5

**Comment by matentzn** [comment]
Closing in favour of https://github.com/mapping-commons/sssom-py/issues/208
